version: '3'

services:

  flask:
    image: webapp-flask
    build:
      context: ./flask
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/app"

  nginx:
    image: webapp-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    links:
      - db
    ports:
      - 5000:6379
    depends_on:
      - flask

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  # screenshot:
  #   build: 
  #     context: ./screenshot
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./screenshot/hush.env
  #   depends_on:
  #     - flask