version: '3'

services:

  flask:
    image: webapp-flask
    build:
      context: ./flask
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/app"

  nginx:
    image: webapp-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:6379
    depends_on:
      - flask

  # screenshot:
  #   build: 
  #     context: ./screenshot
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./screenshot/hush.env