version: '3'

services:

  nginx:
    image: webapp-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:80
      - 8080:6567
    depends_on:
      - ui
      - backend

  ui:
    image: webapp-ui
    build:
      context: ./ui
      dockerfile: Dockerfile-ui
    volumes:
      - "./ui/:/app"
    links:
      - db

  backend:
    image: webapp-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile-backend
    volumes:
      - "./backend/:/app"
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

